/*
*			Copyright Author
* (USE & RESTRICTIONS - Please read COPYRIGHT file)

* Version		: XX.XX
* Date		: 4/20/11 1:09 PM
*/

// Default Package
package DWLProject;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class DW_1_1 extends ViewableDigraph{

    // Add Default Constructor
    public DW_1_1(){
        this("DW_1_1");
    }

    // Add Parameterized Constructor
    public DW_1_1(String name){
        super(name);

// Structure information start
        // Add input port names
        addInport("insert");
        addInport("update");

        // Add output port names
        addOutport("Out Port");

//add test input ports:

        // Initialize sub-components
        ViewableAtomic CubeCoord_1_0 =  new CubeCoord_0_0("CubeCoord_1_0");
        ViewableAtomic Cube_1_0 =  new Cube_0_0("Cube_1_0");
        ViewableAtomic Cube_2_0 =  new Cube_0_0("Cube_2_0");
        ViewableAtomic Cube_3_0 =  new Cube_0_0("Cube_3_0");
        ViewableAtomic Cube_4_0 =  new Cube_0_0("Cube_4_0");

        // Add sub-components
        add(CubeCoord_1_0);
        add(Cube_1_0);
        add(Cube_2_0);
        add(Cube_3_0);
        add(Cube_4_0);

        // Add Couplings
        addCoupling(CubeCoord_1_0, "write", Cube_1_0, "In Port");
        addCoupling(CubeCoord_1_0, "write", Cube_2_0, "In Port");
        addCoupling(CubeCoord_1_0, "write", Cube_3_0, "In Port");
        addCoupling(CubeCoord_1_0, "write", Cube_4_0, "In Port");
        addCoupling(this, "insert", CubeCoord_1_0, "insert");
        addCoupling(this, "Out Port", Cube_1_0, "Out Port");
        addCoupling(this, "Out Port", Cube_2_0, "Out Port");
        addCoupling(this, "Out Port", Cube_3_0, "Out Port");
        addCoupling(this, "Out Port", Cube_4_0, "Out Port");
        addCoupling(this, "update", CubeCoord_1_0, "update");

// Structure information end
        initialize();
        }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(446, 471);
        ((ViewableComponent)withName("Cube_2_0")).setPreferredLocation(new Point(100, 114));
        ((ViewableComponent)withName("Cube_1_0")).setPreferredLocation(new Point(88, 36));
        ((ViewableComponent)withName("CubeCoord_1_0")).setPreferredLocation(new Point(-47, 150));
        ((ViewableComponent)withName("Cube_3_0")).setPreferredLocation(new Point(101, 202));
        ((ViewableComponent)withName("Cube_4_0")).setPreferredLocation(new Point(106, 295));
    }
    }
