/*
*			Copyright Author
* (USE & RESTRICTIONS - Please read COPYRIGHT file)

* Version		: XX.XX
* Date		: 4/20/11 1:09 PM
*/

// Default Package
package DWLProject;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import DWLProject.utils.DWLProperties;

public class DWLProject_0_1 extends ViewableDigraph{

    private static final String FF_OUT = "FFout";
	private static final String LOAD = "load";
	private static final String START = "start";
	private static final String FF_IN = "FFin";
	private static final String STATS = "stats";
	private static final String ERROR_FILE = "errorFile";
	private static final String HALT = "halt";
	private static final String EXT_CAT_IN = "ExtCatIn";
	private static final String EXT_CAT_OUT = "ExtCatOut";

	// Add Default Constructor
    public DWLProject_0_1(){
        this("DWLProject");
    }

    // Add Parameterized Constructor
    public DWLProject_0_1(String name){
        super(name);

// Structure information start
        // Add input port names

        // Add output port names

//add test input ports:

        int numberOfProcessors = Integer.valueOf(DWLProperties.getInstance().getValue("Processors"));
        // Initialize sub-components
        ViewableDigraph EF_1_1 =  new EF_1_1("EF");
        ViewableDigraph DWL_1_1 =  new DWL_1_1("DWL", numberOfProcessors);
        ViewableAtomic DW_1_1 =  new DW_1_1("DW", numberOfProcessors);

        // Add sub-components
        add(EF_1_1);
        add(DWL_1_1);
        add(DW_1_1);

        // Add Couplings
        addCoupling(DWL_1_1, LOAD, DW_1_1, LOAD);
        addCoupling(EF_1_1, FF_OUT, DWL_1_1, FF_IN);
        addCoupling(EF_1_1, START, DWL_1_1, START);
        addCoupling(DW_1_1, STATS, EF_1_1, STATS);
        addCoupling(DWL_1_1, ERROR_FILE, EF_1_1, ERROR_FILE);
        addCoupling(DW_1_1, HALT, DWL_1_1, HALT);
        addCoupling(DWL_1_1, STATS, EF_1_1, STATS);
        addCoupling(DWL_1_1, EXT_CAT_OUT, DW_1_1, EXT_CAT_IN);

// Structure information end
        initialize();
        }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1177, 657);
        ((ViewableComponent)withName("EF")).setPreferredLocation(new Point(40, 56));
        ((ViewableComponent)withName("DW")).setPreferredLocation(new Point(583, 573));
        ((ViewableComponent)withName("DWL")).setPreferredLocation(new Point(455, 55));
    }
    }
